services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mydb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  mydb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Uses the variable from .env
